// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./layout/navbar";
import ReactQueryProvider from "@/app/components/providers/ReactQueryProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="fr"
          // ${geistSans.variable} ${geistMono.variable} 
          className={`h-full antialiased`}
      >
          <body suppressHydrationWarning>
              <ReactQueryProvider>
                  <div className="h-screen bg-[#0e0e10] text-white">
                      <div className="flex flex-1 flex-col">
                          <Navbar />
                          <main className="bg-[#0e0e10]">
                              {children}
                          </main>
                      </div>
                  </div>
              </ReactQueryProvider>
          </body>
      </html>
  );
}
